name: iReport
version:
main: iReport.IReport
commands:
  greport:
    description: Report a griefer logs position of the reported
    usage: /greport <player>
    permission: ireport.greport
    permission-message: You don't have permission!
  hreport:
    description: Report a hacker + what type of hack used
    usage: /hreport <player> <type of hack>
    permission: ireport.hreport
    permission-message: You don't have permission!
  sreport:
    description: Report a swearing player
    usage: /sreport <player>
    permission: ireport.sreport
    permission-message: You don't have permission!
  ireport:
    description: Get plugin help
    usage: /ireport
  reports:
    description: get reports list
    usage: /reports [type] [value]
    permission: ireport.reports
    permission-message: You don't have permission!
  dreport:
    description: deleat a report
    usage: /dreport <UUID>
    permission: ireport.dreport
    permission-message: You don't have permission!